# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\"\x17\n\x06Number\x12\r\n\x05input\x18\x01 \x01(\x05\"\x15\n\x06Result\x12\x0b\n\x03res\x18\x01 \x01(\x05\x32\x33\n\x11SquareRootService\x12\x1e\n\nsquareRoot\x12\x07.Number\x1a\x07.Resultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUMBER._serialized_start=13
  _NUMBER._serialized_end=36
  _RESULT._serialized_start=38
  _RESULT._serialized_end=59
  _SQUAREROOTSERVICE._serialized_start=61
  _SQUAREROOTSERVICE._serialized_end=112
# @@protoc_insertion_point(module_scope)
