# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\"A\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\",\n\x0fGetUsersRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"(\n\x10GetUsersResponse\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"+\n\x13GetUserByIdResponse\x12\x14\n\x05users\x18\x01 \x01(\x0b\x32\x05.User\")\n\x11\x43reateUserRequest\x12\x14\n\x05users\x18\x01 \x01(\x0b\x32\x05.User\"*\n\x12\x43reateUserResponse\x12\x14\n\x05users\x18\x01 \x01(\x0b\x32\x05.User\")\n\x11UpdateUserRequest\x12\x14\n\x05users\x18\x01 \x01(\x0b\x32\x05.User\"*\n\x12UpdateUserResponse\x12\x14\n\x05users\x18\x01 \x01(\x0b\x32\x05.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\x12\x44\x65leteUserResponse\x12\x14\n\x05users\x18\x01 \x01(\x0b\x32\x05.User2\xa1\x02\n\x05Users\x12\x31\n\x08GetUsers\x12\x10.GetUsersRequest\x1a\x11.GetUsersResponse\"\x00\x12:\n\x0bGetUserById\x12\x13.GetUserByIdRequest\x1a\x14.GetUserByIdResponse\"\x00\x12\x37\n\nCreateUser\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\"\x00\x12\x37\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponse\"\x00\x12\x37\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=13
  _USER._serialized_end=78
  _GETUSERSREQUEST._serialized_start=80
  _GETUSERSREQUEST._serialized_end=124
  _GETUSERSRESPONSE._serialized_start=126
  _GETUSERSRESPONSE._serialized_end=166
  _GETUSERBYIDREQUEST._serialized_start=168
  _GETUSERBYIDREQUEST._serialized_end=200
  _GETUSERBYIDRESPONSE._serialized_start=202
  _GETUSERBYIDRESPONSE._serialized_end=245
  _CREATEUSERREQUEST._serialized_start=247
  _CREATEUSERREQUEST._serialized_end=288
  _CREATEUSERRESPONSE._serialized_start=290
  _CREATEUSERRESPONSE._serialized_end=332
  _UPDATEUSERREQUEST._serialized_start=334
  _UPDATEUSERREQUEST._serialized_end=375
  _UPDATEUSERRESPONSE._serialized_start=377
  _UPDATEUSERRESPONSE._serialized_end=419
  _DELETEUSERREQUEST._serialized_start=421
  _DELETEUSERREQUEST._serialized_end=452
  _DELETEUSERRESPONSE._serialized_start=454
  _DELETEUSERRESPONSE._serialized_end=496
  _USERS._serialized_start=499
  _USERS._serialized_end=788
# @@protoc_insertion_point(module_scope)
